INSERT INTO role(title, salary, department) VALUES
    ("Necromancer", 65, 1),
    ("Grand Summoner", 100, 1),
    ("Enchantress", 80, 2),
    ("Blacksmith", 55, 2),
    ("Scroll Scribe", 50, 2),
    ("Wizard", 75, 3),
    ("Spellcrafter", 99, 3),
    ("Wandsmith", 83, 3),
    ("Brewer", 65, 4),
    ("Chemist", 77, 4),
    ("Potion Tester", 34, 4),
    ("Familiar Trainer", 47, 5),
    ("Riding Coach", 42, 5),
    ("Vet", 89, 5);